# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170820_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('filepath', models.FileField(max_length=255, upload_to='video/')),
                ('tags', models.ManyToManyField(to='cms.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
