# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 15:14
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='filepath',
            field=s3direct.fields.S3DirectField(unique=True),
        ),
    ]
