# Generated by Django 2.1.2 on 2018-10-08 06:30

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_content_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='thumb',
            field=s3direct.fields.S3DirectField(blank=True, default=False),
        ),
    ]
